blueprints/api.py
from flask import Blueprint, jsonify

api = Blueprint("api", __name__)


@api.route("/api")
def index():
    endpoints = {"/api": "List of all endpoints", "/api/health-check": "Returns status"}
    return jsonify(endpoints)


@api.route("/api/health-check")
def health_check():
    return jsonify({"status": "OK"})

blueprints/dinner_ideas.py
from flask import Blueprint, request
from flask import render_template

from utilities.login_required import dinner_ideas_required, login_required
from database.dinner_ideas import get_random_dinner_ideas

dinner_ideas = Blueprint("dinner_ideas", __name__)
proj_name = "dinner_ideas"

@dinner_ideas.route(f"/{proj_name}", methods=["GET", "POST"])
@dinner_ideas_required
@login_required
def home():
    food_ideas = []

    if request.method == "POST":
        meal_count_return = request.form.get("meal_count")
        meal_count = int(meal_count_return) if (meal_count_return != '' and meal_count_return is not None) else 7

        food_ideas = get_random_dinner_ideas(meal_count)

    return render_template(f"{proj_name}/dinner_ideas.html", food_ideas=food_ideas, page_title="Dinner Ideas")

blueprints/dress_correct.py
from flask import Blueprint
from flask import render_template

from utilities.login_required import login_required

dress_correct = Blueprint("dress_correct", __name__)
proj_name = "dress_correct"


@dress_correct.route("/dress_correct", methods=["GET", "POST"])
@login_required
def home():
    return render_template(f"{proj_name}/dress_correct.html")

blueprints/weather_app.py
from flask import Blueprint, url_for, redirect, flash
from flask import render_template, request

import database.weather_app as db
from utilities.login_required import weather_app_required, login_required

weather_app = Blueprint("weather_app", __name__)
proj_name = "weather_app"


@weather_app.route("/weather_app", methods=["GET", "POST"])
@weather_app_required
@login_required
def home():
    if request.method == "POST":
        weather = request.form.get("weather")
        wind = request.form.get("wind")
        temperature = request.form.get("temperature")
        try:
            result = db.add_weather_entry(weather, wind, temperature)
            flash((f"Successfully {result}", "success"))
        except Exception as E:
            flash((f"Unsuccessful. Error: {E}", "danger"))
        return redirect(url_for(f"{proj_name}.home"))

    return render_template(f"{proj_name}/weather_app.html")


@weather_app.route("/weather_app/history", methods=["GET", "POST"])
@weather_app_required
@login_required
def history():
    return render_template(f"{proj_name}/history.html")

main.py
import os

import waitress as waitress
from flask import Flask, render_template, url_for, request, flash, redirect, session
from flask_session import Session

import database.users as db_users
from blueprints import api as bp_api
from blueprints import dinner_ideas as bp_dinner_ideas
from blueprints import dress_correct as bp_dress_correct
from blueprints import weather_app as bp_weather_app
from utilities.login_required import login_required

app = Flask(__name__)
# app.config["SESSION_TYPE"] = "memcached"
app.config["SECRET_KEY"] = "super secret key"
sess = Session()
sess.permanent = True
app.register_blueprint(bp_api.api)
app.register_blueprint(bp_weather_app.weather_app)
app.register_blueprint(bp_dinner_ideas.dinner_ideas)
app.register_blueprint(bp_dress_correct.dress_correct)


@app.route("/")
def index():
    return redirect(url_for("home"))


@app.route("/home")
@login_required
def home():
    links = [{"name": "API", "link": url_for("api.index")}]
    links.append({"name": "Dress Correct", "link": url_for("dress_correct.home")})

    if session["weather_app"]:
        links.append({"name": "Weather App", "link": url_for("weather_app.home")})

    if session["dinner_ideas"]:
        links.append({"name": "Dinner Ideas", "link": url_for("dinner_ideas.home")})

    return render_template("index.html", links=links)


@app.route("/login", methods=("POST", "GET"))
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        if db_users.login(email, password):
            flash(("Logged in successfully!", "success"))
            return redirect(url_for("home"))
        else:
            flash(
                (
                    "Invalid details - check username and password and try again!",
                    "warning",
                )
            )

    return render_template("login.html", page_title="Login")


@app.route("/register", methods=("POST", "GET"))
def register():
    if request.method == "POST":
        first_name = request.form.get("first_name")
        last_name = request.form.get("last_name")
        email = request.form.get("email")
        password = request.form.get("password")

        try:
            if db_users.add_user(email, password, first_name, last_name):
                flash(("User added successfully", "success"))
                return redirect(url_for("login"))
        except Exception as E:
            flash((E, "danger"))
            return redirect(url_for("register"))

    return render_template("register.html", page_title="Register")


@app.route("/logout")
def logout():
    session.clear()
    flash(("Logged out successfully", "success"))
    return redirect(url_for("login"))


if __name__ == "__main__":
    print("Starting...")
    port = int(os.environ.get("PORT", 8080))
    waitress.serve(app, host="0.0.0.0", port=port)

templates/_includes/flashes.html
<div class="container text-center">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message, category in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show"
                     role="alert"
                     style="position: fixed; top: 10px; left: 50%; transform: translateX(-50%); z-index: 1000;">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>

templates/dinner_ideas/dinner_ideas.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{page_title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
</head>
<body>
<div class="container text-center mt-4">
    <h1 class="display-1">Dinner Ideas</h1>
    <form method="POST">
        <div class="input-group mb-3">
            <input type="number" class="form-control" placeholder="Enter number of meals needed for this week..." value="7" oninput="validate()" name="meal_count">
        </div>
        <button class="btn btn-primary" type="submit" id="submit_button">Generate Meals</button>
    </form>
</div>

{% if food_ideas != [] %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                    <td><b>Name</b></td>
                    <td><b>Category</b></td>
                </thead>
                <tbody>
                    {% for idea in food_ideas %}
                    <tr>
                        <td>{{idea["name"]}}</td>
                        <td>{{idea["category"]}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endif %}

<script>
    function validate()
    {
        if
    }
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

templates/dress_correct/dress_correct.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DressCorrect</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
</head>
<body>
{% include '_includes/flashes.html' %}
<div class="container-fluid text-center">
    <div class="container">
        <h1 class="display-1">DressCorrect</h1>
    </div>
    <br>
    <div class="container pt-3">
        <div class="row">
            <div class="col">
                <h3>Temperature</h3>
                <h1>Warm</h1>
            </div>
            <div class="col">
                <h3>Chance of Rain</h3>
                <h1>Low</h1>
            </div>
            <div class="col">
                <h3>Wind</h3>
                <h1>Low</h1>
            </div>
        </div>
    </div>
    <div class="container pt-3">
        <div class="row">
            <div class="col">
                <h3>Recommendation</h3>
                <h1>Light Clothing</h1>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

templates/group_planner/_includes/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('home') }}">Group Planner Application</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('home') }}">Home</a>
                </li>
            </ul>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    {{ session["name"].title() }}
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ url_for('changeScreenName') }}">Change Screen Name</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('leaveGroup') }}">Delete my user</a></li>
                    <hr>
                    <li><a class="dropdown-item" href="{{ url_for('logout') }}">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/group_planner/_includes/_toast.html
<div id="mainToast" class="toast align-items-center border-0" role="alert" aria-live="assertive" aria-atomic="true"
     style="width: 100%; max-width: 100%;">
    <div class="d-flex">
        <div class="toast-body" id="toastBody"></div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                aria-label="Close"></button>
    </div>
</div>

templates/group_planner/changeScreenName.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <title>Change Screen Name</title>
</head>
<body>
{% include "_includes/_navbar.html" %}
{% include "_includes/_toast.html" %}

<div class="container mt-4" style="text-align: center">
    <h1>Change Screen Name</h1>
    <form method="POST">
        <div class="form-group mt-4">
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter new name">
            <button type="submit" class="btn btn-dark mt-4">Set new name</button>
        </div>
    </form>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            var message = "{{ messages[0] }}";  // Assuming you only flash one message at a time
            var toast = new bootstrap.Toast(document.querySelector('.toast'));
            toastBody.innerHTML = message;
            if ("{{status}}" == "success") {
                mainToast.classList.add("text-bg-success");
            } else {
                mainToast.classList.add("text-bg-danger");
            }
            toast.show();
            var toastElement = document.querySelector('.toast');
            toastElement.addEventListener('click', function () {
                toast.hide();
            });
        {% endif %}
    {% endwith %}
</script>
</body>
</html>

templates/group_planner/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <style>
        table .selected {
            background-color: #4C4C6D;
            color: white
        }
    </style>
</head>
<body>
{% include "_includes/_navbar.html" %}
{% include '_includes/_toast.html' %}
<div class="grid">
    <div class="row">
        <div class="col-sm">
            <div class="container mt-4" style="text-align: center">
                <div class="row">
                    <div class="col-4 text-end">
                        <button class="btn btn-light me-2" onclick="prevMonth()"><i class="material-icons">keyboard_arrow_left</i>
                        </button>
                    </div>
                    <div class="col-4 text-center">
                        <h2 id="monthDisplay" class="mt-2">Select a Date Range</h2>
                    </div>
                    <div class="col-4">
                        <button class="btn btn-light" onclick="nextMonth()"><i class="material-icons">keyboard_arrow_right</i>
                        </button>
                    </div>
                </div>
                <div id="calendar"></div>
                <form id="dateForm" method="POST"> <!-- Form added -->
                    <input type="hidden" id="selectedDatesInput" name="selectedDates" value="">
                    <!-- Hidden input field to store selected dates -->
                    <input type="hidden" id="removedDatesInput" name="removedDates" value="">
                    <!-- Hidden input field to store removed dates -->
                    <button class="btn btn-dark" onclick="submitSelectedDates()" style="background: #4C4C6D">Update
                        Availability
                    </button>
                    <!-- Button to trigger form submission -->
                </form>
            </div>
        </div>

        <div class="col-sm">
            <div class="container mt-4">
                <h3>Group Availability (Best 5 Days)</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Number Free</th>
                        <th>People Free</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in usersFree %}
                        <tr>
                            <td>{{ item }}</td>
                            <td>{{ usersFree[item]["numberFree"] }}/{{ userCount }}</td>
                            <td>
                                <ul>
                                    {% for person in usersFree[item]["peopleFree"] %}
                                        <li>{{ person.title() }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            var message = "{{ messages[0] }}";  // Assuming you only flash one message at a time
            var toast = new bootstrap.Toast(document.querySelector('.toast'));
            toastBody.innerHTML = message;
            if (true) {
                mainToast.classList.add("text-bg-success");
            } else {
                mainToast.classList.add("text-bg-danger");
            }
            toast.show();
            var toastElement = document.querySelector('.toast');
            toastElement.addEventListener('click', function () {
                toast.hide();
            });
        {% endif %}
    {% endwith %}
</script>

<script>
    var selectedDates = JSON.parse('{{ selected_dates | tojson }}');
    var removedDates = [];
    var currentDate = new Date();
    const todaysDate = new Date();

    function checkInitialSelection(year, month, date) {
        var selectedDate = new Date(year, month, date);

        return selectedDates.some(function (d) {
            date = new Date(d)
            console.log(typeof d)
            return (
                date.getFullYear() === selectedDate.getFullYear() &&
                date.getMonth() === selectedDate.getMonth() &&
                date.getDate() === selectedDate.getDate()
            );
        });
    }

    function createCalendar(year, month) {
        var calendar = document.getElementById("calendar");
        calendar.innerHTML = "";

        var daysInMonth = new Date(year, month + 1, 0).getDate();
        var firstDayIndex = new Date(year, month, 1).getDay();

        var date = 1;

        var table = document.createElement("table");
        table.classList.add("table", "table-bordered", "text-center");

        var thead = document.createElement("thead");
        var tbody = document.createElement("tbody");

        var daysOfWeek = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

        // Create header row with days of the week
        var headerRow = document.createElement("tr");
        for (var i = 0; i < 7; i++) {
            var cell = document.createElement("th");
            cell.textContent = daysOfWeek[i];
            headerRow.appendChild(cell);
        }
        thead.appendChild(headerRow);

        table.appendChild(thead);

        // Create calendar rows
        for (var i = 0; i < 6; i++) {
            var row = document.createElement("tr");

            // Create calendar cells
            for (var j = 0; j < 7; j++) {
                if (i === 0 && j < firstDayIndex) {
                    // Empty cells before the first day of the month
                    var cell = document.createElement("td");
                    row.appendChild(cell);
                } else if (date > daysInMonth) {
                    // Empty cells after the last day of the month
                    break;
                } else {
                    var cell = document.createElement("td");
                    cell.textContent = date;

                    if (checkInitialSelection(year, month, date)) {
                        cell.classList.add("selected");
                    }

                    cell.addEventListener("click", function () {
                        var selectedDate = new Date(Date.UTC(year, month, parseInt(this.textContent)));
                        if (!this.classList.contains("selected")) {
                            this.classList.add("selected");
                            selectedDates.push(selectedDate);
                            removedDates.pop(selectedDate);
                        } else {
                            this.classList.remove("selected");
                            selectedDates.pop(selectedDate);
                            removedDates.push(selectedDate)
                            /*
                            var index = selectedDates.findIndex(function(date) {
                              return date.getTime() === selectedDate.getTime();
                            });
                            if (index > -1) {
                              selectedDates.splice(index, 1);
                            }*/
                        }
                    });

                    /*if (date === todaysDate.getDate() && month === todaysDate.getMonth() && year === todaysDate.getFullYear()) {
                      cell.style.background = "blue";
                      cell.style.color = "white";
                    }*/

                    row.appendChild(cell);
                    date++;
                }
            }

            tbody.appendChild(row);
        }

        table.appendChild(tbody);
        calendar.appendChild(table);
        updateMonthDisplay(month, year);
    }

    function updateMonthDisplay(month, year) {
        var monthDisplay = document.getElementById("monthDisplay");
        monthDisplay.innerHTML = new Date(year, month).toLocaleString('default', {month: 'long', year: 'numeric'});
    }

    function prevMonth() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        createCalendar(currentDate.getFullYear(), currentDate.getMonth());
    }

    function nextMonth() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        createCalendar(currentDate.getFullYear(), currentDate.getMonth());
    }

    function submitSelectedDates() {
        var selectedDatesInput = document.getElementById("selectedDatesInput");
        selectedDatesInput.value = JSON.stringify(selectedDates);

        var removedDatesInput = document.getElementById("removedDatesInput");
        removedDatesInput.value = JSON.stringify(removedDates);

        document.getElementById("dateForm").submit();
    }

    createCalendar(currentDate.getFullYear(), currentDate.getMonth());
</script>
</body>
</html>

templates/group_planner/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Group Planner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{{url_for('static', filename='css/index.css')}}" rel="stylesheet">
</head>
<body style="background: #EEEEEE">

<div class="center-screen">
    <div class="center-fill">
            <h1 class="text-main">RendezView</h1>
            <p class="lead text-main">A better way to plan group meets</p>
            <form method="POST">
                <div class="grid">
                    <div class="row">
                        <div class="col">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="groupCode" name="groupCode"
                                       placeholder="Group Code">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-light">Let's Go!</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GregorApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        body {
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            background: #AAD9BB;
        }
    </style>
</head>
<body>
<div class="container mx-auto text-center">
    {% include '_includes/flashes.html' %}

    <h1>Gregor's Apps</h1>
    <hr>
    <div class="container">
        {% for link in links %}
            <a href="{{ link['link'] }}" class="btn btn-dark">{{ link["name"] }}</a>
        {% endfor %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

templates/inktrigue/inktrigue.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inktrigue</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
</head>
<body>
{% include '_includes/flashes.html' %}
<div class="container text-center">
    <h1>Inktrigue</h1>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

templates/weather_app/_includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Weather App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('weather_app.home') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{{ url_for('weather_app.history') }}">History</a>
                </li>
            </ul>
        </div>
    </div>
</nav>